### ISSUE TITLE
Consider adding an optional "self-revocation" URL to a zcap that can be posted to

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/ocapld.js#17]

**Comment by dlongley** [comment]
Perhaps invoking a zcap with an action of something like `revoke` is another option...

**Comment by mattcollier** [comment]
@dlongley this issue is from summer 2019, is it still applicable?

**Comment by dlongley** [comment]
It's still a concept that might be useful, but considering no one is working on fleshing it out, we can close it.
