### ISSUE TITLE
make bitcore-message an external dependency

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/ocapld.js#18]
ocapld shares bitcore-message along with json-ld however unlike json-ld it's webpack.config.js does not have an:

```
externals: {
      'bitcore-message': {
        amd: 'bitcore-message',
        commonjs: 'bitcore-message',
        commonjs2: 'bitcore-message',
        root: 'bitcoreMessage'
      },
      'node-forge': {
        amd: 'node-forge',
        commonjs: 'node-forge',
        commonjs2: 'node-forge',
        root: 'forge'
      },
      jsonld: 'jsonld'
    }
```

this results in numerous errors in the browser as the crypto object that bitcore-lib expects fails.

**Comment by aljones15** [comment]
Just for future reference when this file is removed from `jsonld-signatures` this issue can be rechecked: https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/suites/EcdsaKoblitzSignature2016.js

**Comment by dlongley** [comment]
This has been externalized in jsonld-signatures. Closing.
