### ISSUE TITLE
Ensure that `invocationTarget` matches expectedTarget(s) throughout chain

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/ocapld.js#38]
It's not clear that the verification process ensures that the `invocationTarget` matches one of the `expectedTarget` values throughout the entire capability chain. It looks like only the root zcap's invocation target may be getting checked against the `expectedTarget`. If that's true, we need:

1. A new failure test where the invocation target changes, when a zcap is delegated, to a value that is not in `expectedTarget`.
2. A new success test where the invocation target changes, when a zcap is delegated, to a value that is expected (i.e., the `expectedTarget` is an array with both the original invocation target in the parent zcap and the new one, demonstrating that both are acceptable).

This will not, however, fully cover supporting the very common URL path "hierarchy" case. We'll have to figure out if we can handle that at the ocapld.js layer or if application logic should be responsible for making sure that situations like this:

```js
chain = [
  // root zcap is for entire "container" "/items"
  {invocationTarget: '/items'},
  // first delegated zcap is for single item 1
  {invocationTarget: '/items/1'},
  // second delegated zcap is for "container" "/items" again (bad!)
  {invocationTarget: '/items'}
]
```

Aren't considered acceptable. We could do all this with special custom caveats, but it would be nice to support it as a core feature for simplicity. One way to do it would be to support passing an object in for `expectedTarget` where each key is a possible root expected target and each value is an *ordered* array of acceptable changes. For example:

```js
expectedTarget: {
  '/items': ['/items/1'],
  '/zcaps/items': ['/zcaps/items/1']
}
```

That may work in a backwards compatible way given that `expectedTarget` may only currently be a string or an array of strings.

**Comment by mattcollier** [comment]
This landed: b98bf0009265ab0eecd6391d7d58809aa8f01411
