### ISSUE TITLE
Rename `allowHierarchicalDelegation` to `allowHierarchicalAttenuation`?

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/ocapld.js#46]
We should bikeshed this real quick before the next release. Do we want the current name or this other one?

**Comment by gannan08** [comment]
Attenuation best captures the intent here. This flag is used to enable delegations that reduce scope.

**Comment by mattcollier** [comment]
I'm fine with `allowHierarchicalAttenuation` however...

What is the aim here?  Is someone supposed to be able to see `allowHierarchicalAttenuation` and have some idea about what it does?  

- *What* is being attenuated?  
  - The `invocationTarget` of the delegation is being attenuated. 
- *How* is it being attenuated?
  - It is being attenuated in an increasingly restrictive way such that the capability of the child is less than or equal to the parent.
  - The RESTful URL paradigm is used to describe the restriction/attentuation.

**Comment by dlongley** [comment]
Some other suggestions given @mattcollier's comments:

`allowHierarchicalInvocationTargetAttenuation: true`
`hierarchicalInvocationTarget: true`

**Comment by mattcollier** [comment]
In an effort to stay under 80 char max-len:
- `allowHierarchicalTargetAttenuation`
- `allowTargetAttenuation`
- `allowInvocationTargetAttenuation`

Is it important to have the word `hierarchical` in the param?  Are there other paradigms for invocationTarget attenuation?

**Comment by dlongley** [comment]
> Is it important to have the word hierarchical in the param? Are there other paradigms for invocationTarget attenuation?

Yes, there are other paradigms for attenuation that is related to the invocation target ... but I think the name `allowInvocationTargetAttenuation` is sufficient. It's *directly* related to how the invocation target is specified as opposed to other things that might be *related* to the invocation target that would be done via custom caveats. So, let's do `allowInvocationTargetAttenuation` if everyone agrees.

**Comment by dlongley** [comment]
Actually, I just checked and since we do `expectedTarget`, let's shorten to `allowTargetAttenuation`.

**Comment by mattcollier** [comment]
@gannan08 the proposal is for `allowTargetAttenuation`.

**Comment by gannan08** [comment]
+1 for `allowTargetAttenuation`.

**Comment by mattcollier** [comment]
OK, I'll update in all the places

**Comment by mattcollier** [comment]
Fix landed: https://github.com/digitalbazaar/ocapld.js/pull/47
